# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph.proto

require 'google/protobuf'

require 'roseflow/tensorflow/definitions/node_def_pb'
require 'roseflow/tensorflow/definitions/function_pb'
require 'roseflow/tensorflow/definitions/versions_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.GraphDef" do
    repeated :node, :message, 1, "tensorflow.NodeDef"
    optional :versions, :message, 4, "tensorflow.VersionDef"
    optional :version, :int32, 3
    optional :library, :message, 2, "tensorflow.FunctionDefLibrary"
  end
end

module Roseflow::Tensorflow::Protobuf
  GraphDef = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.GraphDef").msgclass
end
