# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensor_shape.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tensorflow.TensorShapeProto" do
    repeated :dim, :message, 2, "tensorflow.TensorShapeProto.Dim"
    optional :unknown_rank, :bool, 3
  end
  add_message "tensorflow.TensorShapeProto.Dim" do
    optional :size, :int64, 1
    optional :name, :string, 2
  end
end

module Roseflow::Tensorflow::Protobuf
  TensorShapeProto = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TensorShapeProto").msgclass
  TensorShapeProto::Dim = Google::Protobuf::DescriptorPool.generated_pool.lookup("tensorflow.TensorShapeProto.Dim").msgclass
end
