require "tensorflow/libtensorflow/structs/buffer"
require "tensorflow/libtensorflow/structs/code"
require "tensorflow/libtensorflow/structs/graph"
require "tensorflow/libtensorflow/structs/status"
require "tensorflow/libtensorflow/structs/tensor"
require "tensorflow/libtensorflow/structs/tensor_data"
